# which go to the model you want to use
cfg_root: "/home/ackerman/Workspace/OpenPCDet/tools/cfgs/kitti_models/pv_rcnn.yaml"

# which go to the .pth
model_path: "/home/ackerman/Workspace/OpenPCDet/tools/pv_rcnn_8369.pth"

# result path
result_path: "/home/ackerman/Workspace/RSUDataProcess-2.0/results.txt"

# pointcloud_topic in the bag if you are not sure
# rosbag info xxx.bag check the topic name
pointcloud_topic: "/livox/lidar" # default is from kitti2bag: /velodyne_points

# only the predict probablity over this threshold will be draw a box
threshold: 0.8

# move the lidar center to the front of the car
# if the lidar is in the center of the car, set it to 0
move_lidar_center_x: 0
move_lidar_center_y: 0
height_addtion: 0.5

rx: 0.0
ry: 0.0
rz: 0.0

logitude: 110.510565795
latitude: 19.959623542
height_global: 17.13
yaw: 45.30

x_m: 20
y_m: -5
z_m: -1

y_min: -10
y_max: 5

viz_rate: 1.0